### PR TITLE
Ubuntu build fix

### PR DESCRIPTION
**Pull request by MrNeRF**
- CMAKE version down (does not use recent features. Why raising the bar)?
- Set debug option for debug build. Makes it use breakpoints.
- Specify default build type of not set.
- Remove under linux unnecessary nvidia libs that cause linking errors..
- Does not crash anymore when CUDA PATH is not set.
- Small refactoring.

### CODE REVIEW

**Comment by m-schuetz** [comment]
Thanks! It will take some time to merge this because I'm on vacation until end of november.

**Comment by m-schuetz** [comment]
Looks good to me, what about you @JolifantoBambla ?

**Comment by JolifantoBambla** [comment]
Looks good but according to the docs, the CUDA targets `nvrtc_static` and `nvrtc_builtins_static` which the Windows build links against are only available with CMake version 2.26. I think the Windows build linking against the two is a remnant anyway - if we remove them from the CMakeLists, I think lowering the CMake version is fine.

**Comment by MrNeRF** [comment]
You want me to do it? I can remove the nvrtc stuff but I don't run any Windows installation so I cannot assure if the change breaks something or not.

**Comment by m-schuetz** [comment]
That's fine, I'll check it out for windows. I'm just curious whether nvrtc_static might be required for windows build to make it run on systems without a CUDA installation. The NVRTC docs make it sound a bit like we'll either have to ship the binaries with dlls, or we'll have to include the static lib. 

https://docs.nvidia.com/cuda/nvrtc/index.html

**Comment by MrNeRF** [comment]
I made a clean rebuild. On linux it works. But the change didn't really affect my system. Hope it also works on windows.

**Comment by m-schuetz** [comment]
Just checked it and it works fine for windows. Thanks for the PR!

**Pull request merged**
